커맨드라인 옵션 추가
SyncPulse/syncpulse pull request #13
Opened 2023-10-05 14:38 UTC by longlong75

소스 내 하드코딩 되어 있던 사항들 커맨드라인으로 설정 할 수 있도록 수정

2023-10-06 10:22 UTC, justinjoy requested changes
사소하지만, 코드 컨벤션과 GLib 활용 부분에 대한 수정이 필요합니다.

2023-10-06 10:22 UTC, justinjoy commented on syncpulse/main.c
> +  Argument* argument = malloc(sizeof(Argument));
현재 코드에서는 괜찮습니다만, 파라미터는 지속적으로 확장해서 사용하게 될 가능성이 있으므로 커스텀 구조체를 정의하기 보다는 `GVariantDict`를 사용하는 것을 권장합니다.

2023-10-06 10:22 UTC, justinjoy commented on syncpulse/main.c
> +  Argument* argument = malloc(sizeof(Argument));
두가지 수정 포인트가 있습니다.  1) 코드 컨벤션에따라 `*`은 변수 앞에서 정의해주세요. 2) 메모리 관리는 GLib 함수를 사용해주세요.

메모리 관리도 GLib의 함수를 사용하는 것이 좋습니다. 특히 `g_new0()`는 선언과 초기화를 같이 수행하므로 매우 유용합니다[1]. 

```
  Argument *argument = g_new0(Argument, 1);
```

[1] https://developer-old.gnome.org/glib/stable/glib-Memory-Allocation.html#g-new0

2023-10-06 10:22 UTC, justinjoy commented on syncpulse/main.c
> +  free(argument);
위에서 `g_new0()`로 변경한다면, 여기도 `g_free()`가 되어야 합니다.

2023-10-09 13:31 UTC, longlong75 commented on syncpulse/main.c
> +  Argument* argument = malloc(sizeof(Argument));
GVariantDict를 사용해 본 경험이 없어 추가 질문 드립니다. GVariantDict에 커맨드라인 옵션들을 key/value 형태로 insert하고 다른 부분에서 이를 사용하는 형태의 진행이 맞는지요?
코드 컨벤션 관련 부분 (검토해주신 부분 외 다른 부분에서도 * 위치 수정하였습니다.)과 g_new0 / g_free 부분 수정하였습니다.

2023-10-09 13:39 UTC, justinjoy commented on syncpulse/main.c
> +  Argument* argument = malloc(sizeof(Argument));
> GVariantDict를 사용해 본 경험이 없어 추가 질문 드립니다. GVariantDict에 커맨드라인 옵션들을 key/value 형태로 insert하고 다른 부분에서 이를 사용하는 형태의 진행이 맞는지요?

네 맞습니다. 다만 말씀하신대로 이점만 있는 방법은 아닙니다. 
추가적으로 제안드릴 수 있는 것은, GObject로 만들어서 `g_object_set` 으로 파라미터를 넘겨주는 방식도 생각해 볼 수 있습니다. 
하지만 이 부분은 당장 처리해야하는 부분은 아니기 때문에 천천히 프로젝트의 진행 상황에 따라 편의성을 부여하는 방법으로 고민해보면 좋을 듯 합니다.

2023-10-09 14:02 UTC, justinjoy approved these changes

2023-10-09 14:02 UTC, merged